### ISSUE TITLE
Remapper can not extract data from new ForgeGradle build files

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/Remapper#6]
The line
`println 'MINECRAFT: ' + minecraft.version`
produces a crash because minecraft no longer has a version property.

Currently the best way to get the mcversion I found was this, but I am sure there is a better way:
```
    String version = null;
    for (File f : sourceSets.main.compileClasspath)
	{
          println 'DEP: ' + f.getPath()
	  if(version==null && f.getName().startsWith("forge"))
	  {
		String[] parts = f.getName().split("-");
		if(parts.length >= 4)
		{
			version = parts[1];
		}
	  }
    }
```

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/Remapper/commit/dc2f6114b281786b72f2465156a801050b6ef4b0#diff-c71ad876fb86a6ce08d1d3c0ebf96d79L73
